"""add_payment_info_fields_to_user_model

Revision ID: 88202d3a053d
Revises: 6202082e5d64
Create Date: 2025-09-29 13:33:09.628595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88202d3a053d'
down_revision = '6202082e5d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('branch_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_holder', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_holder')
        batch_op.drop_column('account_number')
        batch_op.drop_column('account_type')
        batch_op.drop_column('branch_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
