"""add_issuer_info_fields_to_users

Revision ID: 97f40bb745e2
Revises: 1a0734b2b82b
Create Date: 2025-10-10 15:37:55.417164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f40bb745e2'
down_revision = '1a0734b2b82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('is_todo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuer_name', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('office_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.String(length=100), nullable=True))
        batch_op.alter_column('pdf_layout',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               server_default='business')
        batch_op.alter_column('pdf_paper_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               server_default='#ffffff')
        batch_op.alter_column('pdf_font_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default='Noto Sans JP')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pdf_font_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('pdf_paper_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
        batch_op.alter_column('pdf_layout',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('contact_info')
        batch_op.drop_column('office_address')
        batch_op.drop_column('issuer_name')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('is_todo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
