"""Add project_name column to invoices table

Revision ID: d1ca214cfb05
Revises: 5ed9c624af99
Create Date: 2025-09-12 10:28:48.927478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ca214cfb05'
down_revision = '5ed9c624af99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
