"""Add monthly snapshot model

Revision ID: 264c518cdcf3
Revises: f59971728522
Create Date: 2025-10-23 10:03:58.217612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264c518cdcf3'
down_revision = 'f59971728522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_month', sa.Date(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_month', 'snapshot_type', name='uq_user_snapshot_month_type')
    )
    with op.batch_alter_table('monthly_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_snapshots_snapshot_month'), ['snapshot_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_snapshots_user_id'), ['user_id'], unique=False)

    # カラムの存在確認を行い、存在する場合のみ削除
    with op.batch_alter_table('users', schema=None) as batch_op:
        # カラムの存在確認と条件付き削除
        columns_to_drop = [
            'secondary_color', 'custom_slug', 'qr_code_filename', 'primary_color',
            'icon_filename', 'twitter_url', 'company_name', 'text_color',
            'youtube_url', 'phone_number', 'bio', 'tiktok_url', 'website_url',
            'profile_public', 'card_color', 'instagram_url', 'threads_url',
            'card_font', 'card_layout', 'layout', 'line_qr_filename',
            'card_style', 'background_color'
        ]
        
        # 各カラムの存在確認と削除
        for column_name in columns_to_drop:
            try:
                # カラムが存在するかチェック
                connection = op.get_bind()
                inspector = sa.inspect(connection)
                columns = [col['name'] for col in inspector.get_columns('users')]
                
                if column_name in columns:
                    batch_op.drop_column(column_name)
                    print(f"Dropped column: {column_name}")
                else:
                    print(f"Column {column_name} does not exist, skipping...")
            except Exception as e:
                print(f"Error checking/dropping column {column_name}: {e}")
                # エラーが発生してもマイグレーションを続行
                pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # downgrade時はカラムの追加のみ（削除されたカラムを復元）
    with op.batch_alter_table('users', schema=None) as batch_op:
        # カラムの存在確認を行い、存在しない場合のみ追加
        columns_to_add = [
            ('background_color', sa.VARCHAR(length=7), True),
            ('card_style', sa.VARCHAR(length=20), True),
            ('line_qr_filename', sa.VARCHAR(length=100), True),
            ('layout', sa.VARCHAR(length=20), True),
            ('card_layout', sa.VARCHAR(length=20), False),
            ('card_font', sa.VARCHAR(length=50), False),
            ('threads_url', sa.VARCHAR(length=255), True),
            ('instagram_url', sa.VARCHAR(length=255), True),
            ('card_color', sa.VARCHAR(length=20), False),
            ('profile_public', sa.BOOLEAN(), False),
            ('website_url', sa.VARCHAR(length=255), True),
            ('tiktok_url', sa.VARCHAR(length=255), True),
            ('bio', sa.TEXT(), True),
            ('phone_number', sa.VARCHAR(length=20), True),
            ('youtube_url', sa.VARCHAR(length=255), True),
            ('text_color', sa.VARCHAR(length=7), True),
            ('company_name', sa.VARCHAR(length=100), True),
            ('twitter_url', sa.VARCHAR(length=255), True),
            ('icon_filename', sa.VARCHAR(length=100), True),
            ('primary_color', sa.VARCHAR(length=7), True),
            ('qr_code_filename', sa.VARCHAR(length=100), True),
            ('custom_slug', sa.VARCHAR(length=50), True),
            ('secondary_color', sa.VARCHAR(length=7), True)
        ]
        
        # 各カラムの存在確認と追加
        for column_name, column_type, nullable in columns_to_add:
            try:
                # カラムが存在するかチェック
                connection = op.get_bind()
                inspector = sa.inspect(connection)
                columns = [col['name'] for col in inspector.get_columns('users')]
                
                if column_name not in columns:
                    batch_op.add_column(sa.Column(column_name, column_type, nullable=nullable))
                    print(f"Added column: {column_name}")
                else:
                    print(f"Column {column_name} already exists, skipping...")
            except Exception as e:
                print(f"Error checking/adding column {column_name}: {e}")
                # エラーが発生してもマイグレーションを続行
                pass

    with op.batch_alter_table('monthly_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_snapshots_snapshot_month'))

    op.drop_table('monthly_snapshots')
    # ### end Alembic commands ###
