"""Add monthly snapshot model

Revision ID: 264c518cdcf3
Revises: f59971728522
Create Date: 2025-10-23 10:03:58.217612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264c518cdcf3'
down_revision = 'f59971728522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_month', sa.Date(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_month', 'snapshot_type', name='uq_user_snapshot_month_type')
    )
    with op.batch_alter_table('monthly_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_snapshots_snapshot_month'), ['snapshot_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_snapshots_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('secondary_color')
        batch_op.drop_column('custom_slug')
        batch_op.drop_column('qr_code_filename')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('icon_filename')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('company_name')
        batch_op.drop_column('text_color')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('bio')
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('website_url')
        batch_op.drop_column('profile_public')
        batch_op.drop_column('card_color')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('threads_url')
        batch_op.drop_column('card_font')
        batch_op.drop_column('card_layout')
        batch_op.drop_column('layout')
        batch_op.drop_column('line_qr_filename')
        batch_op.drop_column('card_style')
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('card_style', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('line_qr_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('layout', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('card_layout', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('card_font', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('threads_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('card_color', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_public', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('text_color', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('icon_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('qr_code_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('custom_slug', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_color', sa.VARCHAR(length=7), nullable=True))

    with op.batch_alter_table('monthly_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_snapshots_snapshot_month'))

    op.drop_table('monthly_snapshots')
    # ### end Alembic commands ###
