"""Add PDF print settings to User model

Revision ID: 6202082e5d64
Revises: 784155763a1e
Create Date: 2025-09-28 12:15:35.641318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6202082e5d64'
down_revision = '784155763a1e'
branch_labels = None
depends_on = None


def upgrade():
    # PostgreSQL/SQLite両対応: 2段階アプローチ
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Step 1: nullable=Trueで追加
        batch_op.add_column(sa.Column('pdf_layout', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pdf_paper_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('pdf_font_family', sa.String(length=50), nullable=True))
    
    # Step 2: デフォルト値設定
    op.execute("UPDATE users SET pdf_layout = 'business' WHERE pdf_layout IS NULL")
    op.execute("UPDATE users SET pdf_paper_color = '#ffffff' WHERE pdf_paper_color IS NULL")
    op.execute("UPDATE users SET pdf_font_family = 'Noto Sans JP' WHERE pdf_font_family IS NULL")
    
    # Step 3: nullable=Falseに変更
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pdf_layout', nullable=False)
        batch_op.alter_column('pdf_paper_color', nullable=False)
        batch_op.alter_column('pdf_font_family', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pdf_font_family')
        batch_op.drop_column('pdf_paper_color')
        batch_op.drop_column('pdf_layout')

    # ### end Alembic commands ###
