"""Add monthly management tables

Revision ID: f59971728522
Revises: 97f40bb745e2
Create Date: 2025-10-21 16:22:37.374362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59971728522'
down_revision = '97f40bb745e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create monthly_targets table
    op.create_table('monthly_targets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('target_month', sa.Date(), nullable=False),
        sa.Column('target_projects', sa.Integer(), nullable=True),
        sa.Column('target_income', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'target_month', name='uq_user_target_month')
    )
    with op.batch_alter_table('monthly_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_targets_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_targets_target_month'), ['target_month'], unique=False)
    
    # Create project_status_history table
    op.create_table('project_status_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('changed_by', sa.Integer(), nullable=True),
        sa.Column('old_status', sa.String(length=20), nullable=True),
        sa.Column('new_status', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('changed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("new_status IN ('proposed', 'contracted', 'completed')", name='ck_project_status_history_new_status')
    )
    with op.batch_alter_table('project_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status_history_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_history_changed_at'), ['changed_at'], unique=False)
    
    # Create invoice_status_history table
    op.create_table('invoice_status_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('changed_by', sa.Integer(), nullable=True),
        sa.Column('old_status', sa.String(length=20), nullable=True),
        sa.Column('new_status', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('changed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("new_status IN ('draft', 'sent', 'paid', 'canceled', 'overdue')", name='ck_invoice_status_history_new_status')
    )
    with op.batch_alter_table('invoice_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_status_history_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status_history_changed_at'), ['changed_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order
    op.drop_table('invoice_status_history')
    op.drop_table('project_status_history')
    op.drop_table('monthly_targets')
    
    # ### end Alembic commands ###
